$(document).ready(function() {
    if(bl !== 'en'){
        chanceLang(bl);
    }
});

let langJson = {
    "en": {
        "page-title":"Curriculum-vitae of Sebastian Poetter",
        "owner-name":"SEBASTIAN POETTER",
        "owner-job-name":"FULL STACK DEVELOPER",
        "contact-title":"CONTACT",
        "contact-email":"<span class=\"d-none\"><a href=\"mailto:email@domain.com\"></a>email@domain.com</span>\n" +
            "<a href=\"&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#112;&#111;&#101;&#116;&#116;&#101;&#114;&#45;%73%65%62%61%73%74%69%61%6E%40%67%6D%78%2E%64%65\">Send me a mail</a>",
        "contact-github":"Find me on Github",
        "hobbies-title":"HOBBIES",
        "hobbies-programming":"Programming",
        "hobbies-swimming":"Swimming",
        "hobbies-hiking":"Hiking",
        "hobbies-game":"Game Developing",
        "hobbies-planting":"Gardening",
        "hobbies-circuit":"IoT tinkering",
        "hobbies-gaming":"Gaming",
        "hobbies-modeling":"3D Modeling",
        "skills-title":"SKILLS",
        "skills-gfx":"Image editing e.g. with ",
        "skills-3d":"Animations e.g. with ",
        "skills-web":"Knowledge of ",
        "skills-team":"Teamleading and Project organisation",
        "skills-circuit":"Knowledge of electrical engineering e.g. with <a href=\"https://www.arduino.cc/\" target=\"_blank\">Arduino</a> and <a href=\"https://wordpress.com/\" target=\"_blank\">Raspberry Pi</a>",
        "footer-title":"IMPRINT",
        "footer-copyright":"BY SEBASTIAN POETTER",
        "footer-policy":"PRIVACY POLICY",
        "footer-library":"USED LIBRARIES",
        "profile-title":"PROFILE",
        "profile-begin":"My name is Sebastian Pötter. I am a student at the University of Applied Sciences (HTWK) in Leipzig and currently studying for a Master's degree in computer science, with a focus on Ki and software development. I can quickly familiarise myself with new projects and am constantly learning more.",
        "profile-other":"Not only computer science is one of my interests, but also other subjects such as biology, chemistry, physics and electrical engineering.",
        "education-title":"EDUCATION",
        "education-secondary-title":"Secondary school (Realschule)",
        "education-secondary-text":"I graduated secondary school in 2014. In Germany the Secondary school is called Realschule and leads to either apprenticeships or on my case to higher education comparable to high schools. Here I started getting interested in Computer and started building simple websites as a hobby.",
        "education-high-title":"High School (Abitur)",
        "education-high-text":"I made my higher education entrance qualification with focus on computer science in 2017. During this time I worked on some simple projects and made free website designs. Here I started to work with the game-development engine Unity and made some smaller 3D-applications.",
        "education-bachelor-title":"University: Bachelor of Science",
        "education-bachelor-text":"I started studying informatics with a focus on software technology and programming techniques in 2017. I got way better at programming, algorithm engineering and software planning. After the course 'principles of mobile robotics' I started experimenting with arduino and raspberry pi boards to create hardware like a weather-station for my home-sever.",
        "education-bachelor-subjects":"Some of my subjects were",
        "education-bachelor-subject-ads":"Algorithms and data structures",
        "education-bachelor-math":"Mathematics for computer scientists",
        "education-bachelor-programming":"Application-/system-/parallel oriented programming",
        "education-bachelor-fp":"Functional programming",
        "education-bachelor-afl":"Automata and formal languages",
        "education-bachelor-ai":"Principles of artificial Intelligence",
        "education-bachelor-mr":"Principles of mobile robotics",
        "education-master-title":"University: Master of Science (aspired for 2022)",
        "education-master-text":"I want to improve the skills I have learned and want to learn more. So I thought that the master degree is the best way for it.",
        "education-master-subjects":"Some of my chosen subjects were",
        "education-master-3d":"3D Capture, Design and Dynamics",
        "education-master-alg":"Algorithm Engineering",
        "education-master-prog":"Progressive Web Apps",
        "education-master-mr":"Mixed Reality & AI",
        "education-master-visu":"Visualization in NaturalSciences and Engineering",
        "experience-title":"EXPERIENCE",
        "experience-small-com":"Multiple commissions of one-page-websites for smaller companies - 2014-2017",
        "experience-landing-page":"Commission of a landing-page for a company in Dresden - 2017",
        "experience-profesco":"Commission of a wordpress-website for the Profesco GmbH (creation and administration) - 2019",
        "experience-internship":"Twelve weeks internship at Profesco GmbH in the IT department - 2020",
        "experience-lefx":"Reworked and updated the wordpress website of the company LeFx GmbH - 2020-2021",
        "experience-velomotion":"Updated the websites of Velomotion GmbH - 2021",
        "experience-overall":"Six years of work experience - 2015 until now",
        "commissions-title":"WHO COMMISSIONED ME",
    },
    "de": {
        "page-title":"Homepage von Sebastian Pötter",
        "owner-name":"Sebastian Pötter",
        "owner-job-name":"FULL STACK DEVELOPER",
        "contact-title":"Kontakt",
        "contact-email":"<span class=\"d-none\"><a href=\"mailto:email@domain.com\"></a>email@domain.com</span>\n" +
            "<a href=\"&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#112;&#111;&#101;&#116;&#116;&#101;&#114;&#45;%73%65%62%61%73%74%69%61%6E%40%67%6D%78%2E%64%65\">Senden Sie mir eine E-Mail</a>",
        "contact-github":"Meine Github-Seite",
        "hobbies-title":"Hobbys",
        "hobbies-programming":"Programmieren",
        "hobbies-swimming":"Schwimmen",
        "hobbies-hiking":"Wandern",
        "hobbies-game":"Spiele-Entwicklung",
        "hobbies-planting":"Gärtnern",
        "hobbies-circuit":"IoT-Bastelei",
        "hobbies-gaming":"Computerspielen",
        "hobbies-modeling":"3D Modellierung",
        "skills-title":"Fähigkeiten",
        "skills-gfx":"Bildbearbeitung z.B. mit ",
        "skills-3d":"Animationen z.B. mit ",
        "skills-web":"Kenntnisse von ",
        "skills-team":"Teamleitung und Projektmanagement",
        "skills-circuit":"Kenntnisse in der Elektrotechnik z.B. mit <a href=\"https://www.arduino.cc/\" target=\"_blank\">Arduino</a> und <a href=\"https://wordpress.com/\" target=\"_blank\">Raspberry Pi</a>",
        "footer-title":"Impressum",
        "footer-copyright":"Erstellt von Sebastian Pötter",
        "footer-policy":"Datenschutzerklärung",
        "footer-library":"Benutze Frameworks",
        "profile-title":"Profil",
        "profile-begin":"Mein Name ist Sebastian Pötter. Ich bin Studierender an der Hochschule für Technik, Wirtschaft und Kultur in Leipzig und aktuell im Masterstudiengang Informatik, Schwerpunkt: Ki und Software-Entwicklung. Ich kann mich schnell in neue Projekte einarbeiten und lerne stetig mehr dazu.",
        "profile-other":"Nicht nur Informatik gehört zu meinen Interessen, sondern auch andere Themen, wie Biologie, Chemie, Physik und Elektrotechnik.",
        "education-title":"Bildungsweg",
        "education-secondary-title":"Realschule",
        "education-secondary-text":"2014 habe ich meinen Realschulabschluss gemacht. Danach entschied ich mich, noch das Abitur zu versuchen. In der Realschulzeit fing ich an, mich für Computer zu interessieren und begann, einfache Webseiten zu erstellen.",
        "education-high-title":"Gymnasium",
        "education-high-text":"Ich habe 2017 mein Abitur mit Schwerpunkt auf Informatik absolviert. Während dieser Zeit habe ich an einigen einfachen Projekten gearbeitet und freie Website-Designs erstellt. Hier fing ich an, mit der 3D-Engine Unity zu arbeiten und erstellte einige kleinere 3D-Anwendungen.",
        "education-bachelor-title":"Universität: Bachelor of Science",
        "education-bachelor-text":"2017 habe ich meinen Bachelor in Informatik mit Schwerpunkt auf Softwaretechnik und Programmiertechniken erreicht. Ich wurde viel besser im Programmieren, Algorithm Engineering und Softwareplanung. Nach dem Kurs 'Grundlagen der mobilen Robotik' habe ich angefangen, mit Arduino- und Raspberry-Pi-Boards zu experimentieren, um Hardware z.B. eine Wetterstation für meinen Home-Sever zu bauen.",
        "education-bachelor-subjects":"Einige meiner Fächer waren",
        "education-bachelor-subject-ads":"Algorithmen und Datenstrukturen",
        "education-bachelor-math":"Mathematik für Informatiker",
        "education-bachelor-programming":"Anwendung-/system-/parallel-orientiere Programmierung ",
        "education-bachelor-fp":"Funktionale Programmierung",
        "education-bachelor-afl":"Automaten und formale Sprachen",
        "education-bachelor-ai":"Prinzipien der künstlichen Intelligenz",
        "education-bachelor-mr":"Prinzipien der Mobilen-Robotik",
        "education-master-title":"Universität: Master of Science (angestrebt für 2022)",
        "education-master-text":"Ich wollte die Fähigkeiten, die ich gelernt habe, vertiefen und verbessern. Also dachte ich mir, dass der Master Studiengang hierfür der beste Weg ist.",
        "education-master-subjects":"Ein paar meiner gewählten Fächer",
        "education-master-3d":"3D-Erfassung, -Design und -Dynamik",
        "education-master-alg":"Algorithmenentwicklung",
        "education-master-prog":"Progressive Web Apps",
        "education-master-mr":"Mixed Reality & Künstliche Intelligenz",
        "education-master-visu":"Visualisierung in Natur- und Ingenieurwissenschaften",
        "experience-title":"Erfahrung",
        "experience-small-com":"Beauftragungen von kleineren One-Page-Webseiten für Unternehmen - 2014-2017",
        "experience-landing-page":"Erstellung einer Webseite für ein Unternehmen in Dresden - 2017",
        "experience-profesco":"Beauftragung einer Wordpress-Seite für die <a href=\"https://www.profesco.de/\">Profesco GmbH</a> (Erstellung und Wartung) - 2019-2021",
        "experience-internship":"12 Wochen Praktikum bei <a href=\"https://www.profesco.de/\">Profesco GmbH</a> in der IT-Abteilung - 2020",
        "experience-lefx":"Überarbeitung und Aktualisierung der Wordpress-Website der <a href=\"https://www.lefx.de/\">LeFx GmbH</a> - 2020-2021",
        "experience-velomotion":"Aktualisierung der Webseite von <a href=\"https://www.velomotion.de/\">Velomotion GmbH</a> - 2021",
        "experience-overall":"Sechs Jahre Berufserfahrung - 2015 bis jetzt",
        "commissions-title":"Referenzen",
    },
    "fr": {
        "page-title":"Curriculum-vitae de Sebastian Pötter",
        "owner-name":"SEBASTIAN POETTER",
        "owner-job-name":"Développeur de pile complète",
        "contact-title":"Données de contact",
        "contact-email":"<span class=\"d-none\"><a href=\"mailto:email@domain.com\"></a>email@domain.com</span>\n" +
            "<a href=\"&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#112;&#111;&#101;&#116;&#116;&#101;&#114;&#45;%73%65%62%61%73%74%69%61%6E%40%67%6D%78%2E%64%65\">Envoyez-moi un e-mail</a>",
        "contact-github":"Retrouvez-moi sur Github",
        "hobbies-title":"hobbies",
        "hobbies-programming":"Programmer",
        "hobbies-swimming":"Nager",
        "hobbies-hiking":"Randonnées",
        "hobbies-game":"Développement de jeux",
        "hobbies-planting":"Jardinage",
        "hobbies-circuit":"IoT bricolage",
        "hobbies-gaming":"Jeux",
        "hobbies-modeling":"Modélisation 3d",
        "skills-title":"compétences",
        "skills-gfx":"L'édition d'images, par exemple avec ",
        "skills-3d":"Animation, par exemple avec ",
        "skills-web":"Connaissance de ",
        "skills-team":"Direction d'équipe et organisation du projet",
        "skills-circuit":"Connaissance de l'ingénierie électrique, par exemple avec <a href=\"https://www.arduino.cc/\" target=\"_blank\">Arduino</a> et <a href=\"https://wordpress.com/\" target=\"_blank\">Raspberry Pi</a>",
        "footer-title":"IMPRESSION",
        "footer-copyright":"par SEBASTIAN PÖTTER",
        "footer-policy":"POLITIQUE DE PROTECTION DE LA VIE PRIVÉE",
        "footer-library":"BIBLIOTHÈQUES UTILISÉES",
        "profile-title":"PROFIL",
        "profile-begin":"Je m'appelle Sebastian Pötter. Je suis étudiant à l'université des sciences appliquées (HTWK) de Leipzig et je prépare actuellement un master en informatique, avec une spécialisation en Ki et en développement de logiciels. Je peux me familiariser rapidement avec de nouveaux projets et j'en apprends toujours plus.",
        "profile-other":"Je ne m'intéresse pas seulement à l'informatique, mais aussi à d'autres matières comme la biologie, la chimie, la physique et le génie électrique.",
        "education-title":"ÉDUCATION",
        "education-secondary-title":"L'école secondaire (Realschule)",
        "education-secondary-text":"En 2017, j'ai obtenu mon diplôme de bachelor en informatique avec une spécialisation en ingénierie logicielle et en techniques de programmation. En Allemagne, l'école secondaire s'appelle Realschule et mène soit à un apprentissage, soit, dans mon cas, à un enseignement supérieur comparable aux lycées. C'est là que j'ai commencé à m'intéresser à l'informatique et que j'ai commencé à construire des sites web simples comme passe-temps.",
        "education-high-title":"Lycée (Abitur)",
        "education-high-text":"J'ai passé mon diplôme d'entrée à l'enseignement supérieur avec spécialisation en informatique en 2017. Pendant cette période, j'ai travaillé sur des projets simples et j'ai conçu des sites web gratuits. J'ai commencé à travailler avec le moteur de développement de jeux Unity et j'ai fait quelques petites applications 3D.",
        "education-bachelor-title":"Université : Licence en sciences",
        "education-bachelor-text":"J'ai commencé à étudier l'informatique en me concentrant sur la technologie des logiciels et les techniques de programmation en 2017. Je me suis beaucoup amélioré en programmation, en ingénierie algorithmique et en planification logicielle. Après le cours \"Principes de la robotique mobile\", j'ai commencé à expérimenter avec des planches de pi arduino et framboise pour créer du matériel comme une station météo pour ma maison - jamais.",
        "education-bachelor-subjects":"Certains de mes sujets étaient",
        "education-bachelor-subject-ads":"Algorithmes et structures de données",
        "education-bachelor-math":"Les mathématiques pour les informaticiens",
        "education-bachelor-programming":"Programmation orientée application/système/parallèle",
        "education-bachelor-fp":"Programmation fonctionnelle",
        "education-bachelor-afl":"Automates et langues formelles",
        "education-bachelor-ai":"Principes de l'intelligence artificielle",
        "education-bachelor-mr":"Principes de la robotique mobile",
        "education-master-title":"Université : Master of Science (aspiré pour 2022)",
        "education-master-text":"Je veux améliorer les compétences que j'ai acquises et je veux en apprendre davantage. J'ai donc pensé que le diplôme de master était le meilleur moyen d'y parvenir.",
        "education-master-subjects":"Voici quelques-uns des sujets que j'ai choisis",
        "education-master-3d":"Capture, conception et dynamique 3D",
        "education-master-alg":"Ingénierie des algorithmes",
        "education-master-prog":"Applications Web progressives",
        "education-master-mr":"Réalité mixte et IA",
        "education-master-visu":"Visualisation en sciences naturelles et en ingénierie",
        "experience-title":"EXPÉRIENCE",
        "experience-small-com":"Commissions multiples de sites web d'une page pour les petites entreprises - 2014-2017",
        "experience-landing-page":"Commande d'une page d'atterrissage pour une entreprise à Dresden - 2017",
        "experience-profesco":"Commande d'un site wordpress-website pour la société Profesco GmbH (création et administration) - 2019",
        "experience-internship":"Stage de douze semaines chez Profesco GmbH dans le département informatique - 2020",
        "experience-lefx":"Refonte et mise à jour du site web wordpress de la société LeFx GmbH - 2020-2021",
        "experience-velomotion":"Mise à jour des sites web de la société Velomotion GmbH - 2021",
        "experience-overall":"Six ans d'expérience professionnelle - de 2015 à aujourd'hui",
        "commissions-title":"QUI M'A COMMANDÉ",
    }
};

let langElements;
langElements = $('[data-i18n]');

function logElements() {
    $.each(langElements, function(index, value) {
        console.log('"'+value.getAttribute('data-i18n')+ '":"'+value.innerText+'",');
        //console.log('"'+value.getAttribute('data-i18n')+ '":"",');
    });
}

function chanceLang(lang) {
    switch (lang) {
        case "en":
            break;
        case "de":
            break;
        case "fr":
            break;
        default:
            return;
    }
    document.documentElement.lang = lang;
    $.each(langElements, function(index, value) {
        let currentObj = value.getAttribute('data-i18n');
        value.innerHTML = langJson[lang][currentObj];
    });
}
